name: CI Mentoria

# Gatilho manual
on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Iniciar servidor de mocks
        run: npm run mock-server &

      - name: Iniciar servidor da aplicação
        run: npm run server &

      - name: Executar testes com Cypress
        run: npx cypress run

      - name: Fazer upload dos relatórios do Cypress
        if: always() # executa mesmo que os testes falhem
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports

          
  
